version: 2
updates:
  - package-ecosystem: "gradle"
    target-branch: main
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    target-branch: main
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
