name: Publish

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "Version"
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build with Gradle
      run: |
        ./gradlew package -P net.matsudamper.device_capture.version=${Env:VERSION}
      env:
        VERSION: ${{ github.event.inputs.VERSION }}
    - name: release
      run: |
        gh release create --generate-notes ${Env:VERSION} ./build/compose/binaries/main/msi/DeviceCapture-${Env:VERSION}.msi
      env:
        GITHUB_TOKEN: ${{ github.token }}
        VERSION: ${{ github.event.inputs.VERSION }}
