name: Publish

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "Version"
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: release
      run: |
        gh release upload $VERSION build/libs/device_capture-jvm-${VERSION}.jar
      env:
        GITHUB_TOKEN: ${{ github.token }}
        VERSION: ${{ github.event.inputs.VERSION }}
