name: Publish

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "Version"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build with Gradle
      run: |
        ./gradlew build -P net.matsudamper.device_capture.version=${VERSION}
      env:
        VERSION: ${{ github.event.inputs.VERSION }}
    - name: release
      run: |
        gh release create $VERSION ./build/libs/device_capture-jvm-${VERSION}.jar
      env:
        GITHUB_TOKEN: ${{ github.token }}
        VERSION: ${{ github.event.inputs.VERSION }}
